owner-name: srivatsan

server:
  port: 8000
  servlet:
    context-path: /api/v1/

spring:
  application:
    name: studentapi
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/student
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
#  cloud:
#    consul:
#      config:
#        enabled: false
#      host: ${CONSUL_HOST:localhost}
#      port: ${CONSUL_PORT:8500}
#    discovery:
#      enabled: true


school:
  school-id: 1787
  school-name: SRMJV
  school-region: India

admin:
  username: srivatsan
  password: password

